### PR TITLE
Fixed typos in implementation of validationPropertiesToIgnore option.

### PR DESCRIPTION
**Pull request by VShingala**
Found these issues while usage of the corresponding API. Let me know if anything is missing.

### CODE REVIEW

**Comment by LuisTejedaS** [comment]
hi, this was intentional it is not a typo The optional chaining operator (?.) enables you to read the value of a property located deep within a chain of connected objects without having to check that each reference in the chain is valid.

The ?. operator is like the . chaining operator, except that instead of causing an error if a reference is nullish (null or undefined), the expression short-circuits with a return value of undefined. When used with function calls, it returns undefined if the given function does not exist.


 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

please let me know if you prefer we change the nulllish check

**Comment by LuisTejedaS** [comment]
> @LuisTejedaS Got it. I didn't have knowledge on this as It seems optional chaining is only supported for nodejs v>=14. This is the thing that we need to answer in `package.json`, about what's the least version of node that this module can handle. For `openapi-to-postman` it's v>=8 ([source](https://github.com/postmanlabs/openapi-to-postman/blob/develop/package.json#L111)).
> 
> Can we use anything optional here? It would be great if we could have support for at least v10 of nodejs as it's still active. version.
hi @VShingala 
Yeah we could use a normal nullish check, would you like me to update this branch/PR or a make a new one?

**Comment by VShingala** [comment]
@LuisTejedaS That would be great, you can create new PR or use this one either if fine. Can we add the least supported version of node in `package.json` as done in `openapi-to-postman` module?

**Comment by LuisTejedaS** [comment]
@VShingala @Carlos-Veloz @erfemega team please check all the thread, i added the information in package.json and change the nullish check for compatibility

**Review by LuisTejedaS — APPROVED** [review]

**Review by Carlos-Veloz — APPROVED** [review]

**Comment by VShingala** [comment]
@LuisTejedaS Changes looks good to me. 👍

**Review by erfemega — APPROVED** [review]

**Pull request merged**
